### ISSUE TITLE
Encoding error when installing on Windows

### ISSUE THREAD

**Issue by jxrossel** [TriOptima/tri.table#10]
Hi,

When pip-ing on Windows, I get:

```
Collecting tri.table
  Downloading tri.table-4.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\rosselj\AppData\Local\Temp\pip-build-pffzr5hj\tri.table\setup.py", line 7, in <module>
        readme = open('README.rst').read()
      File "C:\PortableSoftware\WinPython3-5\python-3.5.3.amd64\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4826: character maps to <undefined>
```

As far as I've seen, it might be related to some special characters in auxiliary text files (README and such). Probably, the quotation marks in the README.rst file (look for “just display columns x, y and z somehow”). I'd like to test your very promising package, but I'm stuck here...

**Comment by boxed** [comment]
We've pushed a new release (4.1.2) for you that should fix this. Funnily it was a confluence of problems:

1. python on windows uses cp1252 encoding by default
2. but not in python 3.6 anymore!
3. we had inadvertently put in smart quotes instead of straight quotes in the readme. Oops
4. we didn't open the readme with a specific encoding specified

phew! We've fixed 3 and 4 :P

**Comment by jxrossel** [comment]
Nice, that was fast ! ... and it works, even nicer. Thanks !

**Comment by boxed** [comment]
Great! If you have any questions feel free to mail me at boxed@killingar.net or post issues here. There's a bit of magic in tri.table which makes people a bit confused at time when trying to do more advanced stuff :P
